Map<String, int> platcode = {
  'HACKERRANK': 63,
  'HACKEREARTH': 73,
  'CODECHEF': 2,
  'CODEFORCES': 1,
  'LEETCODE': 102,
  'TOPCODER': 12,
  'KAGGLE': 74,
  'PROJECT EULER': 65,
  'GOOGLE COMPETITIONS': 35,
  'ATCODER': 93
};
